version: '3.5'
services:
  scraper:
    container_name: webReview
    build:
      context: .
      dockerfile: ./app/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - /habr_hubs.db:/habr_hubs.db